name: Deploy to AWS Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to Server 1
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@*** 'bash -s' < ./deploy.sh
      env:
        SERVER: ${{ secrets.SERVER1 }}
    
    - name: Test Server 1 Deployment
      run: |
        curl -f http://${{ secrets.SERVER1 }}/ || exit 1

    - name: Switch Load Balancer to Server 1
      run: |
        aws elbv2 modify-target-group-attributes --target-group-arn arn:aws:elasticloadbalancing:ap-south-1:123456789012:targetgroup/my-target-group/1234567890123456 --attributes Key=stickiness.enabled,Value=true

    - name: Deploy to Server 2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER2 }} 'bash -s' < ./deploy.sh
      env:
        SERVER: ${{ secrets.SERVER2 }}
    
    - name: Test Server 2 Deployment
      run: |
        curl -f http://${{ secrets.SERVER2 }}/ || exit 1

    - name: Switch Load Balancer to Server 2
      run: |
        aws elbv2 modify-target-group-attributes --target-group-arn arn:aws:elasticloadbalancing:ap-south-1:123456789012:targetgroup/my-target-group/1234567890123456 --attributes Key=stickiness.enabled,Value=true
